pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent{
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){
                    sh 'export GOCACHE="${WORKSPACE}/bugtracker-backend/.cache/go-build"'
                    sh 'go test -v ./...'
                }
            }
        }
    }
}