pipeline {
    agent any

    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello World'
                sh 'echo "Hello Jenkins"'
                sh 'date'
            }
        }
    }
}